// Shared MapLibre crayon style override. Both `/preview` and the
// production map import from here.
//
// Direction:
//   - Palette: BLACK / WHITE / GREEN / BLUE (+ greys for roads).
//   - Roads: light-grey crayon-textured strokes with offset wobble
//     clones (lighter + darker shade).
//   - Buildings: 3D walls + thin dark crayon outline traced from above.
//   - Park + water FILLS get layered-noise grain (natural crayon
//     coverage, no motifs).
//   - Polygon corners SOFTENED via thick same-colour line + line-blur
//     so the rounded edge fades into the bg rather than reading as a
//     visible border.
//   - Labels via tiered system in installLabelOverride.

import type maplibregl from 'maplibre-gl';
import type { LayerSpecification } from 'maplibre-gl';

// Single source of truth for the MapLibre label font. Must match the
// directory name under app/public/fonts/<MAP_FONT>/ (generated by
// scripts/generate-map-pbfs.js). To swap the map's label face, run
// the script with the new TTF + name, then update this constant.
const MAP_FONT = 'Annex Fam Normal';

// ---------------------------------------------------------------------
// Palette
// ---------------------------------------------------------------------

// Palette tuned to the in-app pixel-art home screen: pastel grass green,
// pale sky blue, soft cards. Keeps crayon dark for legibility but the
// nature fills move from "vivid sticker" to "pastel storybook".
//
// THE PALING WAS A DEBT THIS MAP NO LONGER OWES.
//
// Saturation was cut by 45% here because territory used to be painted
// over the walking map in a dozen saturated colours, and a vivid green
// park read as somebody's claim rather than as a park. That is not the
// arrangement any more: territory is a lens now, it only paints in play
// mode, and play mode has its own palette (PLAY_PALETTE below) which
// takes the hue out for exactly that reason. So the walking map was
// paying for a conflict that had moved somewhere else — a grey-green
// city under a bright white HUD, on an app about going outside.
//
// Saturation goes back x1.9, to 0.49 base — where it was before the
// paling — with LIGHTNESS UNTOUCHED, so the parks and the river get
// their colour back without getting heavier. Measured the same way the
// cut was, CIE76:
//
//              water vs park   vs paper   base saturation
//   original        66           34/57         0.48
//   paled           25           20/27         0.26
//   here            46           24/38         0.49
//
// PLAY_PALETTE is untouched by this: it names its own greens and blues,
// so the territory view stays as quiet as it was.
export const LIGHT_PALETTE = {
  paper: '#ffffff',
  crayon: '#2a2a2a',
  greyRoad: '#d4d4d4',
  green: '#c0de9e',
  greenDark: '#a0cc80',
  greenLight: '#e4f2cd',
  blue: '#acd8ef',
  blueDark: '#90c3dc',
  blueLight: '#d6edf7',
  // Road wobble clone colours — kept close to greyRoad so the offset
  // copies read as a subtle "double line" texture instead of as a
  // stack of dark cables crossing the city.
  roadWobbleLight: '#e8e8e8',
  roadWobbleDark: '#bcbcbc',
  // Tinted speckles for the paper-tooth multiply overlay — warmer +
  // less saturated to match the soft pastel feel.
  paperSpeckleA: '#b4a578',
  paperSpeckleB: '#d6caa6',
  // Label tier colours.
  labelText: '#2a2a2a',
  labelHalo: '#ffffff',
  labelWater: '#3a7da0',
  labelStreet: '#3a3a3a',
  // Multiply overlay opacity (lightens darken effect).
  paperOpacity: 0.48,
  // Sky dome + horizon haze: a blue dome fading to a light neutral-grey
  // horizon that matches the grey depth-fog layer so the join is seamless.
  //
  // The dome deepens with the parks and the river below it — raising its
  // saturation alone did nothing, because at lightness 0.91 the blue was
  // already clipping. Taking it down to 0.88 is what makes it read as
  // sky. The horizon and the fog stay exactly where they were: they ARE
  // the join, and the dome now simply has further to fade.
  sky: {
    skyColor: '#cadff6',
    horizonColor: '#e6eaee',
    fogColor: '#e9ebed',
  },
};

export type Palette = typeof LIGHT_PALETTE;

// The same map with its hue taken out, for the territory view.
//
// Owner colours are the subject there — a dozen of them, drawn over the
// city — and a green park under a green territory is two greens arguing.
// Every hue below is LIGHT_PALETTE's own, desaturated to 0.35 of its
// saturation with lightness untouched, so what goes is the colour and
// not the shape: you can still see where the river runs and where the
// parks are, by tone.
//
// Measured the same way the desaturation above was, CIE76 against the
// paper:
//
//                park vs water   park vs paper   water vs paper   base sat
//   walking map       24.5            26.8            19.5          0.262
//   here              10.0            22.7            17.8          0.092
//   fully grey         5.8            23.0            17.2          0.000
//
// 0.35 rather than 0: the structure argument is the same one the file
// makes above — pale everything the whole way and the river reads as a
// wide grey street. At 10 the water is still about four JNDs cooler
// than a lawn, which is enough to tell them apart and not enough to
// fight an owner's paint. Roads, paper and labels are already neutral
// and are left alone.
export const PLAY_PALETTE: Palette = {
  ...LIGHT_PALETTE,
  green: '#bec4b8',
  greenDark: '#a5ad9f',
  greenLight: '#e0e3dc',
  blue: '#c7cfd4',
  blueDark: '#afb8bd',
  blueLight: '#e4e8e9',
  labelWater: '#5b737f',
};


const ROAD_WIDTH_SCALE = 0.22;

// ---------------------------------------------------------------------
// Canvas pattern generators
// ---------------------------------------------------------------------

function rng(seed: number): () => number {
  let s = seed >>> 0 || 1;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 0xffffffff;
  };
}

function ctxFor(w: number, h: number) {
  const c = document.createElement('canvas');
  c.width = w;
  c.height = h;
  return { c, ctx: c.getContext('2d')! };
}

function noiseFill(opts: {
  size: number;
  base: string;
  darker: string;
  lighter: string;
  seed: number;
  blobs: number;
  blobAlpha: number;
  blobRadius: [number, number];
  dots: number;
  dotAlpha: [number, number];
  dotSize: [number, number];
  speckles: number;
  speckleAlpha: [number, number];
}): ImageData {
  const {
    size,
    base,
    darker,
    lighter,
    seed,
    blobs,
    blobAlpha,
    blobRadius,
    dots,
    dotAlpha,
    dotSize,
    speckles,
    speckleAlpha,
  } = opts;
  const { c, ctx } = ctxFor(size, size);
  ctx.fillStyle = base;
  ctx.fillRect(0, 0, size, size);
  const r = rng(seed);
  for (let i = 0; i < blobs; i++) {
    ctx.fillStyle = r() > 0.5 ? darker : lighter;
    ctx.globalAlpha = blobAlpha * (0.5 + r() * 1.0);
    const x = r() * size;
    const y = r() * size;
    const radius = blobRadius[0] + r() * (blobRadius[1] - blobRadius[0]);
    ctx.beginPath();
    ctx.arc(x, y, radius, 0, Math.PI * 2);
    ctx.fill();
  }
  for (let i = 0; i < dots; i++) {
    ctx.fillStyle = r() > 0.55 ? darker : lighter;
    ctx.globalAlpha = dotAlpha[0] + r() * (dotAlpha[1] - dotAlpha[0]);
    const x = r() * size;
    const y = r() * size;
    const s = dotSize[0] + r() * (dotSize[1] - dotSize[0]);
    ctx.fillRect(x, y, s, s);
  }
  for (let i = 0; i < speckles; i++) {
    ctx.fillStyle = r() > 0.6 ? darker : lighter;
    ctx.globalAlpha =
      speckleAlpha[0] + r() * (speckleAlpha[1] - speckleAlpha[0]);
    const x = Math.floor(r() * size);
    const y = Math.floor(r() * size);
    ctx.fillRect(x, y, 1, 1);
  }
  ctx.globalAlpha = 1;
  return ctx.getImageData(0, 0, size, size);
}

function parkPattern(p: Palette): ImageData {
  return noiseFill({
    size: 256,
    base: p.green,
    darker: p.greenDark,
    lighter: p.greenLight,
    seed: 7,
    blobs: 18,
    blobAlpha: 0.1,
    blobRadius: [25, 80],
    dots: 950,
    dotAlpha: [0.16, 0.45],
    dotSize: [0.5, 1.9],
    speckles: 2400,
    speckleAlpha: [0.06, 0.22],
  });
}

function waterPattern(p: Palette): ImageData {
  return noiseFill({
    size: 256,
    base: p.blue,
    darker: p.blueDark,
    lighter: p.blueLight,
    seed: 13,
    blobs: 22,
    blobAlpha: 0.11,
    blobRadius: [25, 80],
    dots: 950,
    dotAlpha: [0.16, 0.42],
    dotSize: [0.5, 1.9],
    speckles: 2400,
    speckleAlpha: [0.06, 0.22],
  });
}

function roadPattern(p: Palette): ImageData {
  const w = 128;
  const h = 16;
  const { c, ctx } = ctxFor(w, h);
  ctx.fillStyle = p.greyRoad;
  ctx.fillRect(0, 0, w, h);
  const r = rng(23);
  for (let i = 0; i < 110; i++) {
    ctx.fillStyle = p.paper;
    ctx.globalAlpha = 0.32 + r() * 0.4;
    const x = r() * w;
    const y = r() * h;
    const s = 0.4 + r() * 1.0;
    ctx.fillRect(x, y, s, s);
  }
  // Keep some darker grain but never near-black — roads should read
  // as a light pencil hatch, not as a stack of dark cables.
  for (let i = 0; i < 160; i++) {
    ctx.fillStyle = r() > 0.5 ? '#b8b8b8' : '#9a9a9a';
    ctx.globalAlpha = 0.06 + r() * 0.14;
    const x = Math.floor(r() * w);
    const y = Math.floor(r() * h);
    ctx.fillRect(x, y, 1, 1);
  }
  ctx.globalAlpha = 1;
  return ctx.getImageData(0, 0, w, h);
}

export function generatePaperTextureUrl(palette: Palette): string {
  const size = 512;
  const c = document.createElement('canvas');
  c.width = size;
  c.height = size;
  const ctx = c.getContext('2d')!;
  ctx.fillStyle = palette.paper;
  ctx.fillRect(0, 0, size, size);
  const r = rng(99);
  for (let i = 0; i < 11000; i++) {
    ctx.globalAlpha = 0.05 + r() * 0.22;
    ctx.fillStyle =
      r() > 0.6 ? palette.paperSpeckleA : palette.paperSpeckleB;
    const x = Math.floor(r() * size);
    const y = Math.floor(r() * size);
    ctx.fillRect(x, y, 1, 1);
  }
  ctx.globalAlpha = 1;
  return c.toDataURL('image/png');
}

// ---------------------------------------------------------------------
// MapLibre helpers
// ---------------------------------------------------------------------

function addImg(
  map: maplibregl.Map,
  id: string,
  img: ImageData,
  pixelRatio = 1,
) {
  if (map.hasImage(id)) map.removeImage(id);
  map.addImage(id, img, { pixelRatio });
}

function clear(map: maplibregl.Map, id: string, prop: string) {
  try {
    (map.setPaintProperty as (l: string, p: string, v: unknown) => void)(
      id,
      prop,
      undefined,
    );
  } catch {
    /* ignore */
  }
}

// ---------------------------------------------------------------------
// Style override entry point. Idempotent — safe to call again with a
// different palette. Re-styles existing liberty layers and injects our
// own (polygon softening outlines, road wobble clones, building
// outlines).
// ---------------------------------------------------------------------

export function applyCrayonOverride(
  map: maplibregl.Map,
  palette: Palette,
  lang: 'uk' | 'en' = 'uk',
): void {
  addImg(map, 'crayon-park', parkPattern(palette), 1);
  addImg(map, 'crayon-water', waterPattern(palette), 1);
  addImg(map, 'crayon-road', roadPattern(palette), 1);

  // Atmospheric sky + horizon fog. At the steep game pitch the top of the
  // screen shows sky, and distant buildings fade into the horizon haze for
  // real depth (vs. piling flat against the page colour). atmosphere-blend
  // (zoom-driven, the documented pattern) keeps the haze strong when
  // zoomed out and eases it back as you zoom in close.
  if (typeof map.setSky === 'function') {
    map.setSky({
      'sky-color': palette.sky.skyColor,
      // Soft, wide blends so the horizon is a broad fogged band rather
      // than a hard line — sky melts gradually into a tall haze that the
      // distant city dissolves into.
      'sky-horizon-blend': 0.9,
      'horizon-color': palette.sky.horizonColor,
      'horizon-fog-blend': 0.5,
      'fog-color': palette.sky.fogColor,
      // Fog rises high from the ground so the far field is swallowed well
      // before the true horizon — "limits" how far you read into depth.
      'fog-ground-blend': 0.9,
      // Kept subtle — the grey depth-fog custom layer does the heavy
      // lifting now; setSky mainly draws the sky dome.
      'atmosphere-blend': [
        'interpolate',
        ['linear'],
        ['zoom'],
        13,
        0.6,
        18,
        0.35,
      ] as unknown as number,
    });
  }

  const layers = map.getStyle().layers ?? [];
  const buildingLayer = layers.find(
    (l) => (l as { 'source-layer'?: string })['source-layer'] === 'building',
  );
  const buildingSource = (buildingLayer as { source?: string } | undefined)
    ?.source;

  type PolygonInfo = {
    baseId: string;
    source: string;
    sourceLayer: string;
    filter: unknown;
    color: string;
  };
  const polygonsToSoften: PolygonInfo[] = [];

  for (const l of layers) {
    const id = l.id;
    const sl = (l as { 'source-layer'?: string })['source-layer'];
    const type = l.type;
    const lower = id.toLowerCase();

    if (id.startsWith('soften-') || id.startsWith('wobble-') || id.startsWith('crayon-')) {
      // Layers we've injected previously — re-style updates them via
      // setPaintProperty in the appropriate branch below if needed.
      continue;
    }

    if (type === 'background') {
      clear(map, id, 'background-pattern');
      map.setPaintProperty(id, 'background-color', palette.paper);
      continue;
    }

    if (sl === 'water') {
      if (type === 'fill') {
        // Flat colour, not the crayon noise pattern. The grain earned its
        // keep when the fills were the richest thing on the map; under
        // the territory field's multiply stain the speckles and blobs
        // showed through every claim and read as dirt on the colour.
        clear(map, id, 'fill-pattern');
        map.setPaintProperty(id, 'fill-color', palette.blue);
        map.setPaintProperty(id, 'fill-opacity', 1);
        const src = (l as { source?: string }).source;
        const filt = (l as { filter?: unknown }).filter;
        if (src)
          polygonsToSoften.push({
            baseId: id,
            source: src,
            sourceLayer: 'water',
            filter: filt,
            color: palette.blue,
          });
        continue;
      }
      map.setLayoutProperty(id, 'visibility', 'none');
      continue;
    }

    if (sl === 'building') {
      if (type === 'fill') {
        clear(map, id, 'fill-pattern');
        map.setPaintProperty(id, 'fill-color', palette.paper);
        map.setPaintProperty(id, 'fill-opacity', 1);
      } else if (type === 'fill-extrusion') {
        clear(map, id, 'fill-extrusion-pattern');
        map.setPaintProperty(id, 'fill-extrusion-color', palette.paper);
        // Fully opaque so nothing shows through to grey them; the built-in
        // vertical gradient still gives walls their depth shading.
        map.setPaintProperty(id, 'fill-extrusion-opacity', 1);
      }
      continue;
    }

    const isLanduseFill =
      (sl === 'landuse' || sl === 'landcover') && type === 'fill';
    const isParkLayer = sl === 'park' && type === 'fill';
    if (isLanduseFill || isParkLayer) {
      const isGreen =
        isParkLayer ||
        /park|grass|wood|forest|cemetery|recreation|pitch|meadow|farm|garden|scrub|playground|nature/.test(
          lower,
        );
      if (isGreen) {
        // Flat colour — same reasoning as the water fill above.
        clear(map, id, 'fill-pattern');
        map.setPaintProperty(id, 'fill-color', palette.green);
        map.setPaintProperty(id, 'fill-opacity', 1);
        const src = (l as { source?: string }).source;
        const filt = (l as { filter?: unknown }).filter;
        if (src && sl)
          polygonsToSoften.push({
            baseId: id,
            source: src,
            sourceLayer: sl,
            filter: filt,
            color: palette.green,
          });
      } else {
        map.setLayoutProperty(id, 'visibility', 'none');
      }
      continue;
    }

    if (sl === 'transportation' && type === 'line') {
      const isCasing =
        lower.includes('casing') ||
        lower.endsWith('-bg') ||
        lower.endsWith('_bg') ||
        lower.includes('outline');
      if (isCasing) {
        map.setLayoutProperty(id, 'visibility', 'none');
        continue;
      }
      // Non-road transportation classes — rail, aerialway, ferry,
      // transit, tram, etc. — also live under the `transportation`
      // source-layer. If we apply the road pattern to them they read
      // as wide ghostly diagonals crossing the city. Hide them.
      const isNonRoad =
        /(^|[_-])(rail|railway|aerialway|cable|gondola|chair|funicular|ferry|transit|tram|monorail|subway|pier)([_-]|$)/.test(
          lower,
        );
      if (isNonRoad) {
        map.setLayoutProperty(id, 'visibility', 'none');
        continue;
      }
      // Service / construction / track / raceway — driveways, alleys,
      // dead-end utility roads. Pure noise at any zoom; hide.
      const isAlwaysHidden =
        /(^|[_-])(service|track|construction|raceway)([_-]|$)/.test(lower);
      if (isAlwaysHidden) {
        map.setLayoutProperty(id, 'visibility', 'none');
        continue;
      }
      // Path / footway / pedestrian / cycleway / steps / bridleway —
      // sidewalk doubles along streets + footpaths through parks. They
      // clutter the map (a mess of thin doubled lines) at every zoom, so
      // hide them outright rather than zoom-gating them in close.
      const isPathish =
        /(^|[_-])(path|footway|pedestrian|cycleway|steps|bridleway)([_-]|$)/.test(
          lower,
        );
      if (isPathish) {
        map.setLayoutProperty(id, 'visibility', 'none');
        continue;
      }
      clear(map, id, 'line-color');
      clear(map, id, 'line-dasharray');
      map.setPaintProperty(id, 'line-pattern', 'crayon-road');
      map.setPaintProperty(id, 'line-opacity', 1);
      const curW = map.getPaintProperty(id, 'line-width');
      const newW: unknown = ['max', 0.4, ['*', ROAD_WIDTH_SCALE, curW ?? 1]];
      try {
        (
          map.setPaintProperty as (l: string, p: string, v: unknown) => void
        )(id, 'line-width', newW);
      } catch {
        if (typeof curW === 'number') {
          map.setPaintProperty(id, 'line-width', curW * ROAD_WIDTH_SCALE);
        }
      }
      try {
        map.setLayoutProperty(id, 'line-cap', 'round');
        map.setLayoutProperty(id, 'line-join', 'round');
      } catch {
        /* not all line layers accept these layout props */
      }
      continue;
    }

    // LABEL TIERS. text-field is locked to a single language at a
    // time (vs the bilingual "Kyiv / Київ" the OSM tile ships) — the
    // dog talks in one language, the map should match. UK is the
    // Kyiv-pilot default; flip via the in-profile language toggle.
    // Coalesce chain falls through to whatever variant the tile has
    // so unlabelled features (or missing :uk on minor streets) still
    // render with the bare name field.
    const localisedLabel =
      lang === 'uk'
        ? ['coalesce', ['get', 'name:uk'], ['get', 'name'], ['get', 'name:en']]
        : ['coalesce', ['get', 'name:en'], ['get', 'name']];
    if (sl === 'place' && type === 'symbol') {
      try {
        map.setLayoutProperty(id, 'text-field', localisedLabel);
        map.setLayoutProperty(id, 'text-font', [MAP_FONT]);
        map.setPaintProperty(id, 'text-color', palette.labelText);
        map.setPaintProperty(id, 'text-halo-color', palette.labelHalo);
        map.setPaintProperty(id, 'text-halo-width', 2);
        map.setPaintProperty(id, 'text-halo-blur', 0.5);
        map.setLayoutProperty(id, 'text-letter-spacing', 0.08);
      } catch {
        /* skip */
      }
      continue;
    }
    if (sl === 'water_name' && type === 'symbol') {
      try {
        map.setLayoutProperty(id, 'text-field', localisedLabel);
        map.setLayoutProperty(id, 'text-font', [MAP_FONT]);
        map.setPaintProperty(id, 'text-color', palette.labelWater);
        map.setPaintProperty(id, 'text-halo-color', palette.labelHalo);
        map.setPaintProperty(id, 'text-halo-width', 2);
        map.setLayoutProperty(id, 'text-letter-spacing', 0.08);
      } catch {
        /* skip */
      }
      continue;
    }
    if (sl === 'transportation_name' && type === 'symbol') {
      try {
        map.setLayoutProperty(id, 'visibility', 'visible');
        (
          map as unknown as {
            setLayerZoomRange: (id: string, min: number, max: number) => void;
          }
        ).setLayerZoomRange(id, 15, 24);
        map.setLayoutProperty(id, 'text-field', localisedLabel);
        map.setLayoutProperty(id, 'text-font', [MAP_FONT]);
        map.setPaintProperty(id, 'text-color', palette.labelStreet);
        map.setPaintProperty(id, 'text-halo-color', palette.labelHalo);
        map.setPaintProperty(id, 'text-halo-width', 1.8);
        map.setLayoutProperty(id, 'text-letter-spacing', 0.05);
      } catch {
        /* skip */
      }
      continue;
    }

    map.setLayoutProperty(id, 'visibility', 'none');
  }

  // Soft polygon halos.
  for (const p of polygonsToSoften) {
    const softId = `soften-${p.baseId}`;
    if (map.getLayer(softId)) {
      map.setPaintProperty(softId, 'line-color', p.color);
      continue;
    }
    try {
      map.addLayer({
        id: softId,
        type: 'line',
        source: p.source,
        'source-layer': p.sourceLayer,
        ...(p.filter !== undefined ? { filter: p.filter } : {}),
        paint: {
          'line-color': p.color,
          'line-width': [
            'interpolate', ['linear'], ['zoom'],
            10, 0.6,
            14, 1.6,
            18, 3.5,
          ],
          'line-blur': [
            'interpolate', ['linear'], ['zoom'],
            10, 1.5,
            14, 4,
            18, 9,
          ],
          'line-opacity': 0.9,
        },
        layout: {
          'line-cap': 'round',
          'line-join': 'round',
        },
      } as LayerSpecification);
    } catch {
      /* skip silently */
    }
  }

  // Road wobble clones — light + dark grey offset shadows of each
  // transportation line. Skip layers we just hid (rail, paths, etc.)
  // so we don't draw wobble shadows under invisible features.
  const roadIds: string[] = [];
  for (const l of map.getStyle().layers ?? []) {
    const sl = (l as { 'source-layer'?: string })['source-layer'];
    if (
      l.type === 'line' &&
      sl === 'transportation' &&
      !l.id.startsWith('wobble-') &&
      (l.layout?.visibility ?? 'visible') !== 'none'
    ) {
      roadIds.push(l.id);
    }
  }
  for (const baseId of roadIds) {
    const base = map.getLayer(baseId) as
      | (LayerSpecification & {
          source?: string;
          'source-layer'?: string;
          filter?: unknown;
          minzoom?: number;
          maxzoom?: number;
        })
      | undefined;
    if (!base || !base.source || !base['source-layer']) continue;
    const lineWidth = map.getPaintProperty(baseId, 'line-width');
    // Single subtle wobble companion at +1.5 px — just enough to
    // hint at a doubled crayon stroke, not enough to read as a
    // separate cable. Two clones at ±5 with blur 2 stacked into the
    // "wires across the city" effect.
    const variants: Array<{ suffix: string; offset: number; color: string }> = [
      { suffix: 'lo', offset: 1.5, color: palette.roadWobbleLight },
    ];
    for (const v of variants) {
      const id = `wobble-${baseId}-${v.suffix}`;
      if (map.getLayer(id)) {
        map.setPaintProperty(id, 'line-color', v.color);
        continue;
      }
      try {
        map.addLayer(
          {
            id,
            type: 'line',
            source: base.source,
            'source-layer': base['source-layer'],
            ...(base.filter !== undefined ? { filter: base.filter } : {}),
            ...(base.minzoom !== undefined ? { minzoom: base.minzoom } : {}),
            ...(base.maxzoom !== undefined ? { maxzoom: base.maxzoom } : {}),
            paint: {
              'line-color': v.color,
              'line-width': lineWidth,
              'line-offset': v.offset,
              'line-opacity': 0.7,
              'line-blur': 0.8,
            },
            layout: {
              'line-cap': 'round',
              'line-join': 'round',
            },
          } as LayerSpecification,
          baseId,
        );
      } catch {
        /* skip */
      }
    }
  }

  // Building outline — currently hidden to see how the map reads
  // without the dark trace. Flip BUILDING_OUTLINE_OPACITY back to
  // a non-zero value (0.3 — 0.55 was the prior tuning) to restore.
  const BUILDING_OUTLINE_OPACITY = 0;
  if (
    BUILDING_OUTLINE_OPACITY > 0 &&
    buildingSource &&
    !map.getLayer('crayon-building-outline')
  ) {
    const outlineLayer: LayerSpecification = {
      id: 'crayon-building-outline',
      type: 'line',
      source: buildingSource,
      'source-layer': 'building',
      minzoom: 13,
      paint: {
        'line-color': palette.crayon,
        'line-opacity': BUILDING_OUTLINE_OPACITY,
        'line-width': [
          'interpolate', ['linear'], ['zoom'],
          13, 0.4,
          16, 0.9,
          19, 1.4,
        ],
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    } as LayerSpecification;
    map.addLayer(outlineLayer);
  } else if (buildingSource && map.getLayer('crayon-building-outline')) {
    // Layer exists from a prior render — drop it if we've disabled
    // outlines, otherwise re-sync its colour.
    if (BUILDING_OUTLINE_OPACITY <= 0) {
      map.removeLayer('crayon-building-outline');
    } else {
      map.setPaintProperty('crayon-building-outline', 'line-color', palette.crayon);
      map.setPaintProperty('crayon-building-outline', 'line-opacity', BUILDING_OUTLINE_OPACITY);
    }
  }
}

// Show / hide the street-name labels (the `transportation_name` symbol
// layers). At the steep game pitch, road names tilt into the perspective
// and clutter the distance, so MapView hides them past the cull pitch and
// brings them back when the camera flattens out. Kept here (not in
// MapView) so the source-layer matching lives next to the rest of the
// label styling.
export function setStreetLabelsVisible(
  map: maplibregl.Map,
  visible: boolean,
): void {
  for (const l of map.getStyle().layers ?? []) {
    const sl = (l as { 'source-layer'?: string })['source-layer'];
    if (sl === 'transportation_name' && l.type === 'symbol') {
      try {
        map.setLayoutProperty(l.id, 'visibility', visible ? 'visible' : 'none');
      } catch {
        /* layer not ready / removed — skip */
      }
    }
  }
}

// ---------------------------------------------------------------------
// Style fetcher — fetch liberty's style.json, swap its glyphs URL to
// our locally-hosted Caveat PBFs, hand the mutated style to MapLibre.
// Returns the style ready to pass to `new maplibregl.Map({ style })`.
// ---------------------------------------------------------------------

export async function fetchCrayonStyleSpec(): Promise<unknown> {
  const resp = await fetch('https://tiles.openfreemap.org/styles/liberty');
  const style = (await resp.json()) as Record<string, unknown>;
  style.glyphs = `${window.location.origin}/fonts/{fontstack}/{range}.pbf`;
  return style;
}

// ---------------------------------------------------------------------
// Paper-tooth overlay sync — anchors a CSS overlay's background-position
// to a fixed lat/lng so the texture travels with the geography on pan
// (not "dirty glass" effect).
// ---------------------------------------------------------------------

export interface OverlayRef {
  current: HTMLDivElement | null;
}

export function installPaperOverlaySync(
  map: maplibregl.Map,
  overlayRef: OverlayRef,
  anchorLng: number,
  anchorLat: number,
): () => void {
  const anchor = { lng: anchorLng, lat: anchorLat };
  const initialPx = map.project(anchor);
  const sync = () => {
    const el = overlayRef.current;
    if (!el) return;
    const px = map.project(anchor);
    el.style.backgroundPosition = `${px.x - initialPx.x}px ${px.y - initialPx.y}px`;
  };
  map.on('move', sync);
  sync();
  return () => {
    map.off('move', sync);
  };
}
