// Shared MapLibre crayon style override. Both `/preview` and the
// production map import from here.
//
// Direction:
//   - Palette: BLACK / WHITE / GREEN / BLUE (+ greys for roads).
//   - Roads: light-grey crayon-textured strokes with offset wobble
//     clones (lighter + darker shade).
//   - Buildings: 3D walls + thin dark crayon outline traced from above.
//   - Park + water FILLS get layered-noise grain (natural crayon
//     coverage, no motifs).
//   - Polygon corners SOFTENED via thick same-colour line + line-blur
//     so the rounded edge fades into the bg rather than reading as a
//     visible border.
//   - Labels via tiered system in installLabelOverride.

import type maplibregl from 'maplibre-gl';
import type { LayerSpecification } from 'maplibre-gl';

// Single source of truth for the MapLibre label font. Must match the
// directory name under app/public/fonts/<MAP_FONT>/ (generated by
// scripts/generate-map-pbfs.js). To swap the map's label face, run
// the script with the new TTF + name, then update this constant.
const MAP_FONT = 'Annex Fam Normal';

// ---------------------------------------------------------------------
// Palette
// ---------------------------------------------------------------------

// Palette tuned to the in-app pixel-art home screen: pastel grass green,
// pale sky blue, soft cards. Keeps crayon dark for legibility but the
// nature fills move from "vivid sticker" to "pastel storybook".
//
// THE PALING WAS A DEBT THIS MAP NO LONGER OWES.
//
// Saturation was cut by 45% here because territory used to be painted
// over the walking map in a dozen saturated colours, and a vivid green
// park read as somebody's claim rather than as a park. That is not the
// arrangement any more: territory is a lens now, it only paints in play
// mode, and play mode has its own palette (PLAY_PALETTE below) which
// takes the hue out for exactly that reason. So the walking map was
// paying for a conflict that had moved somewhere else — a grey-green
// city under a bright white HUD, on an app about going outside.
//
// Saturation goes back x1.9, to 0.49 base — where it was before the
// paling — with LIGHTNESS UNTOUCHED, so the parks and the river get
// their colour back without getting heavier. Measured the same way the
// cut was, CIE76:
//
//              water vs park   vs paper   base saturation
//   original        66           34/57         0.48
//   paled           25           20/27         0.26
//   here            46           24/38         0.49
//
// PLAY_PALETTE is untouched by this: it names its own greens and blues,
// so the territory view stays as quiet as it was.
export const LIGHT_PALETTE = {
  paper: '#ffffff',
  crayon: '#2a2a2a',
  greyRoad: '#d4d4d4',
  green: '#c0de9e',
  greenDark: '#a0cc80',
  greenLight: '#e4f2cd',
  blue: '#acd8ef',
  blueDark: '#90c3dc',
  blueLight: '#d6edf7',
  // Road wobble clone colours — kept close to greyRoad so the offset
  // copies read as a subtle "double line" texture instead of as a
  // stack of dark cables crossing the city.
  roadWobbleLight: '#e8e8e8',
  roadWobbleDark: '#bcbcbc',
  // Tinted speckles for the paper-tooth multiply overlay — warmer +
  // less saturated to match the soft pastel feel.
  paperSpeckleA: '#b4a578',
  paperSpeckleB: '#d6caa6',
  // Label tier colours.
  labelText: '#2a2a2a',
  labelHalo: '#ffffff',
  labelWater: '#3a7da0',
  labelStreet: '#3a3a3a',
  // Multiply overlay opacity (lightens darken effect).
  paperOpacity: 0.48,
  // INK EDGE. Null here, and that is not an oversight.
  //
  // Park and water polygons get a soft halo in their OWN colour, which is
  // what makes a flat fill sit on the page instead of being stamped onto
  // it. Put a pen line round the same fill and it stops reading as a
  // drawn shape and starts reading as a border — the fill is doing the
  // work, and the edge is arguing with it.
  //
  // The paper map is the other way round: the fill is white, so the edge
  // IS the shape. PAPER_PALETTE sets this; every coloured palette leaves
  // it null and keeps the halo.
  outline: null as string | null,
  outlineOpacity: 0,
  // Building footprints traced in ink, and the extruded walls dropped.
  // Zero on the coloured maps, where buildings are volumes.
  buildingOutline: 0,
  // How much of the tile style's own road width to keep. 0.22 suits a
  // textured band, which is what a crayon road is; ink needs more (see
  // PAPER_PALETTE).
  roadScale: 0.22,
  // Sky dome + horizon haze: a blue dome fading to a light neutral-grey
  // horizon that matches the grey depth-fog layer so the join is seamless.
  //
  // The dome deepens with the parks and the river below it — raising its
  // saturation alone did nothing, because at lightness 0.91 the blue was
  // already clipping. Taking it down to 0.88 is what makes it read as
  // sky. The horizon and the fog stay exactly where they were: they ARE
  // the join, and the dome now simply has further to fade.
  sky: {
    skyColor: '#cadff6',
    horizonColor: '#e6eaee',
    fogColor: '#e9ebed',
  },
};

export type Palette = typeof LIGHT_PALETTE;

// The same map with its hue taken out, for the territory view.
//
// Owner colours are the subject there — a dozen of them, drawn over the
// city — and a green park under a green territory is two greens arguing.
// Every hue below is LIGHT_PALETTE's own, desaturated to 0.35 of its
// saturation with lightness untouched, so what goes is the colour and
// not the shape: you can still see where the river runs and where the
// parks are, by tone.
//
// Measured the same way the desaturation above was, CIE76 against the
// paper:
//
//                park vs water   park vs paper   water vs paper   base sat
//   walking map       24.5            26.8            19.5          0.262
//   here              10.0            22.7            17.8          0.092
//   fully grey         5.8            23.0            17.2          0.000
//
// 0.35 rather than 0: the structure argument is the same one the file
// makes above — pale everything the whole way and the river reads as a
// wide grey street. At 10 the water is still about four JNDs cooler
// than a lawn, which is enough to tell them apart and not enough to
// fight an owner's paint. Roads, paper and labels are already neutral
// and are left alone.
export const PLAY_PALETTE: Palette = {
  ...LIGHT_PALETTE,
  green: '#bec4b8',
  greenDark: '#a5ad9f',
  greenLight: '#e0e3dc',
  blue: '#c7cfd4',
  blueDark: '#afb8bd',
  blueLight: '#e4e8e9',
  labelWater: '#5b737f',
};

// THE PAPER MAP — the walking city as a pen drawing (experiment).
//
// Same construction as the profile scene: white page, nothing but line.
// No texture anywhere — no crayon grain in the fills, no dry-pen fleck in
// the roads, no paper tooth over the top — and no volume: the extruded
// city and the mist it stood in are switched off (PAPER_MAP in
// constants/experiments.ts), and buildings are traced as footprints
// instead. Everything that carried tone carries none, so what is left to
// tell a park from a river from a block is outline and line weight.
//
// Every fill is `paper`. That is the whole idea and it is also the whole
// risk: a lawn and the Dnipro are both white, and only their edge and
// their scale separate them. Weight is what does the separating —
// buildings finest, polygon edges mid, roads carrying the street
// hierarchy the tiles already encode.
//
// Roads go DARK, which is the one inversion here: `greyRoad` is the ink
// the street network is drawn in, not a wash it is filled with. On the
// paper map they take no pattern at all (see the transportation branch).
export const PAPER_PALETTE: Palette = {
  ...LIGHT_PALETTE,
  green: '#ffffff',
  greenDark: '#ffffff',
  greenLight: '#ffffff',
  blue: '#ffffff',
  blueDark: '#ffffff',
  blueLight: '#ffffff',
  greyRoad: '#3a3a3a',
  outline: '#2a2a2a',
  outlineOpacity: 0.85,
  buildingOutline: 0.55,
  // Streets lead the drawing. At the crayon scale the ink lines came out
  // finer than the building footprints — and footprints outnumber streets
  // heavily, so the page read as a field of blocks with the network lost
  // inside it. The tile style's own class hierarchy is kept; only the
  // overall weight moves.
  roadScale: 0.34,
  labelWater: '#4c4c4c',
  // White page all the way up. With the ground fog gone this is MapLibre's
  // own sky dome, so it is flat by construction — which is what a drawing
  // has above the horizon.
  sky: {
    skyColor: '#ffffff',
    horizonColor: '#ffffff',
    fogColor: '#ffffff',
  },
};

// The palette the last applyCrayonOverride() ran with. The WebGL layers
// (ground fog's sky dome) need the sky colours, and they render on their
// own clock rather than being called with a palette — this is how they
// ask. Read via getActivePalette(); never mutate the object it returns.
let activePalette: Palette = LIGHT_PALETTE;

export function getActivePalette(): Palette {
  return activePalette;
}

// SCALING A WIDTH THAT IS ITSELF AN EXPRESSION.
//
// The obvious wrapper — ['max', 0.4, ['*', SCALE, <current>]] — is
// invalid the moment <current> is a zoom ramp, and the tile style ramps
// every road class: MapLibre allows a `zoom` expression only at the top
// level of a `step`/`interpolate`, so the whole declaration is rejected
// and the layer keeps the width it had. The old catch below rescued only
// the plain-number case, so EVERY RAMPED ROAD KEPT ITS FULL WIDTH —
// four to five times the intended weight. The console has carried one
// `line-width` validation error per road layer the whole time; under a
// pale grey wash nobody could see the result, and in ink you can.
//
// So scale the ramp's OUTPUTS and leave its structure alone.
function scaleWidth(cur: unknown, k: number): unknown {
  const scale = (n: number) => Math.max(0.4, n * k);
  if (typeof cur === 'number') return scale(cur);
  if (!Array.isArray(cur)) return scale(1);
  const op = cur[0];
  if (op === 'interpolate' || op === 'interpolate-hcl' || op === 'interpolate-lab') {
    // ['interpolate', <interpolation>, <input>, stop, out, stop, out, …]
    const out: unknown[] = cur.slice(0, 3);
    for (let i = 3; i < cur.length; i += 2) out.push(cur[i], scaleWidth(cur[i + 1], k));
    return out;
  }
  if (op === 'step') {
    // ['step', <input>, out0, stop, out, stop, out, …]
    const out: unknown[] = [cur[0], cur[1], scaleWidth(cur[2], k)];
    for (let i = 3; i < cur.length; i += 2) out.push(cur[i], scaleWidth(cur[i + 1], k));
    return out;
  }
  // Any other expression — a `match` on class, a `case`. It cannot hold a
  // zoom ramp of its own (that would already be invalid), so the wrapper
  // is safe here.
  return ['max', 0.4, ['*', k, cur]];
}

// Polygon edge geometry. The halo is a wide, blurred bloom in the fill's
// own colour; the ink edge is a narrow, near-crisp pen line. Same layer,
// two jobs — see `outline` in LIGHT_PALETTE.
const HALO_WIDTH: unknown = [
  'interpolate', ['linear'], ['zoom'],
  10, 0.6,
  14, 1.6,
  18, 3.5,
];
const HALO_BLUR: unknown = [
  'interpolate', ['linear'], ['zoom'],
  10, 1.5,
  14, 4,
  18, 9,
];
const INK_WIDTH: unknown = [
  'interpolate', ['linear'], ['zoom'],
  10, 0.7,
  14, 1.2,
  18, 2.1,
];
const INK_BLUR: unknown = 0.3;

// ---------------------------------------------------------------------
// Canvas pattern generators
// ---------------------------------------------------------------------

function rng(seed: number): () => number {
  let s = seed >>> 0 || 1;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 0xffffffff;
  };
}

function ctxFor(w: number, h: number) {
  const c = document.createElement('canvas');
  c.width = w;
  c.height = h;
  return { c, ctx: c.getContext('2d')! };
}

function noiseFill(opts: {
  size: number;
  base: string;
  darker: string;
  lighter: string;
  seed: number;
  blobs: number;
  blobAlpha: number;
  blobRadius: [number, number];
  dots: number;
  dotAlpha: [number, number];
  dotSize: [number, number];
  speckles: number;
  speckleAlpha: [number, number];
}): ImageData {
  const {
    size,
    base,
    darker,
    lighter,
    seed,
    blobs,
    blobAlpha,
    blobRadius,
    dots,
    dotAlpha,
    dotSize,
    speckles,
    speckleAlpha,
  } = opts;
  const { c, ctx } = ctxFor(size, size);
  ctx.fillStyle = base;
  ctx.fillRect(0, 0, size, size);
  const r = rng(seed);
  for (let i = 0; i < blobs; i++) {
    ctx.fillStyle = r() > 0.5 ? darker : lighter;
    ctx.globalAlpha = blobAlpha * (0.5 + r() * 1.0);
    const x = r() * size;
    const y = r() * size;
    const radius = blobRadius[0] + r() * (blobRadius[1] - blobRadius[0]);
    ctx.beginPath();
    ctx.arc(x, y, radius, 0, Math.PI * 2);
    ctx.fill();
  }
  for (let i = 0; i < dots; i++) {
    ctx.fillStyle = r() > 0.55 ? darker : lighter;
    ctx.globalAlpha = dotAlpha[0] + r() * (dotAlpha[1] - dotAlpha[0]);
    const x = r() * size;
    const y = r() * size;
    const s = dotSize[0] + r() * (dotSize[1] - dotSize[0]);
    ctx.fillRect(x, y, s, s);
  }
  for (let i = 0; i < speckles; i++) {
    ctx.fillStyle = r() > 0.6 ? darker : lighter;
    ctx.globalAlpha =
      speckleAlpha[0] + r() * (speckleAlpha[1] - speckleAlpha[0]);
    const x = Math.floor(r() * size);
    const y = Math.floor(r() * size);
    ctx.fillRect(x, y, 1, 1);
  }
  ctx.globalAlpha = 1;
  return ctx.getImageData(0, 0, size, size);
}

function parkPattern(p: Palette): ImageData {
  return noiseFill({
    size: 256,
    base: p.green,
    darker: p.greenDark,
    lighter: p.greenLight,
    seed: 7,
    blobs: 18,
    blobAlpha: 0.1,
    blobRadius: [25, 80],
    dots: 950,
    dotAlpha: [0.16, 0.45],
    dotSize: [0.5, 1.9],
    speckles: 2400,
    speckleAlpha: [0.06, 0.22],
  });
}

function waterPattern(p: Palette): ImageData {
  return noiseFill({
    size: 256,
    base: p.blue,
    darker: p.blueDark,
    lighter: p.blueLight,
    seed: 13,
    blobs: 22,
    blobAlpha: 0.11,
    blobRadius: [25, 80],
    dots: 950,
    dotAlpha: [0.16, 0.42],
    dotSize: [0.5, 1.9],
    speckles: 2400,
    speckleAlpha: [0.06, 0.22],
  });
}

function roadPattern(p: Palette): ImageData {
  const w = 128;
  const h = 16;
  const { c, ctx } = ctxFor(w, h);
  ctx.fillStyle = p.greyRoad;
  ctx.fillRect(0, 0, w, h);
  const r = rng(23);
  for (let i = 0; i < 110; i++) {
    ctx.fillStyle = p.paper;
    ctx.globalAlpha = 0.32 + r() * 0.4;
    const x = r() * w;
    const y = r() * h;
    const s = 0.4 + r() * 1.0;
    ctx.fillRect(x, y, s, s);
  }
  // Keep some darker grain but never near-black — roads should read
  // as a light pencil hatch, not as a stack of dark cables.
  for (let i = 0; i < 160; i++) {
    ctx.fillStyle = r() > 0.5 ? '#b8b8b8' : '#9a9a9a';
    ctx.globalAlpha = 0.06 + r() * 0.14;
    const x = Math.floor(r() * w);
    const y = Math.floor(r() * h);
    ctx.fillRect(x, y, 1, 1);
  }
  ctx.globalAlpha = 1;
  return ctx.getImageData(0, 0, w, h);
}

export function generatePaperTextureUrl(palette: Palette): string {
  const size = 512;
  const c = document.createElement('canvas');
  c.width = size;
  c.height = size;
  const ctx = c.getContext('2d')!;
  ctx.fillStyle = palette.paper;
  ctx.fillRect(0, 0, size, size);
  const r = rng(99);
  for (let i = 0; i < 11000; i++) {
    ctx.globalAlpha = 0.05 + r() * 0.22;
    ctx.fillStyle =
      r() > 0.6 ? palette.paperSpeckleA : palette.paperSpeckleB;
    const x = Math.floor(r() * size);
    const y = Math.floor(r() * size);
    ctx.fillRect(x, y, 1, 1);
  }
  ctx.globalAlpha = 1;
  return c.toDataURL('image/png');
}

// ---------------------------------------------------------------------
// MapLibre helpers
// ---------------------------------------------------------------------

function addImg(
  map: maplibregl.Map,
  id: string,
  img: ImageData,
  pixelRatio = 1,
) {
  if (map.hasImage(id)) map.removeImage(id);
  map.addImage(id, img, { pixelRatio });
}

function clear(map: maplibregl.Map, id: string, prop: string) {
  try {
    (map.setPaintProperty as (l: string, p: string, v: unknown) => void)(
      id,
      prop,
      undefined,
    );
  } catch {
    /* ignore */
  }
}

// ---------------------------------------------------------------------
// Style override entry point. Idempotent — safe to call again with a
// different palette. Re-styles existing liberty layers and injects our
// own (polygon softening outlines, road wobble clones, building
// outlines).
// ---------------------------------------------------------------------

export function applyCrayonOverride(
  map: maplibregl.Map,
  palette: Palette,
  lang: 'uk' | 'en' = 'uk',
): void {
  activePalette = palette;
  const ink = palette.outline;

  // Flat colour, not the crayon noise pattern. The grain earned its keep
  // when the fills were the richest thing on the map; under the territory
  // field's multiply stain the speckles and blobs showed through every
  // claim and read as dirt on the colour. On the paper map there is no
  // colour to grain: the fill is the page and the edge is the shape.
  //
  // fill-outline-color is set to the fill's own colour rather than left
  // alone. The tile style gives `park` an outline of rgb(95,208,100) — a
  // vivid green a good deal louder than any fill this file has ever
  // painted — and nothing here had ever overridden it. Under a green park
  // it passed as a slightly keener edge; on the white page it is a bright
  // green hairline round every park in the frame, which is how it was
  // finally noticed. Same for the building fill's beige rim.
  const paintFill = (id: string, colour: string) => {
    clear(map, id, 'fill-pattern');
    map.setPaintProperty(id, 'fill-color', colour);
    map.setPaintProperty(id, 'fill-outline-color', colour);
    map.setPaintProperty(id, 'fill-opacity', 1);
  };

  addImg(map, 'crayon-park', parkPattern(palette), 1);
  addImg(map, 'crayon-water', waterPattern(palette), 1);
  addImg(map, 'crayon-road', roadPattern(palette), 1);

  // Atmospheric sky + horizon fog. At the steep game pitch the top of the
  // screen shows sky, and distant buildings fade into the horizon haze for
  // real depth (vs. piling flat against the page colour). atmosphere-blend
  // (zoom-driven, the documented pattern) keeps the haze strong when
  // zoomed out and eases it back as you zoom in close.
  if (typeof map.setSky === 'function') {
    map.setSky({
      'sky-color': palette.sky.skyColor,
      // Soft, wide blends so the horizon is a broad fogged band rather
      // than a hard line — sky melts gradually into a tall haze that the
      // distant city dissolves into.
      'sky-horizon-blend': 0.9,
      'horizon-color': palette.sky.horizonColor,
      'horizon-fog-blend': 0.5,
      'fog-color': palette.sky.fogColor,
      // Fog rises high from the ground so the far field is swallowed well
      // before the true horizon — "limits" how far you read into depth.
      'fog-ground-blend': 0.9,
      // Kept subtle — the grey depth-fog custom layer does the heavy
      // lifting now; setSky mainly draws the sky dome.
      'atmosphere-blend': [
        'interpolate',
        ['linear'],
        ['zoom'],
        13,
        0.6,
        18,
        0.35,
      ] as unknown as number,
    });
  }

  const layers = map.getStyle().layers ?? [];
  const buildingLayer = layers.find(
    (l) => (l as { 'source-layer'?: string })['source-layer'] === 'building',
  );
  const buildingSource = (buildingLayer as { source?: string } | undefined)
    ?.source;

  type PolygonInfo = {
    baseId: string;
    source: string;
    sourceLayer: string;
    filter: unknown;
    color: string;
  };
  const polygonsToSoften: PolygonInfo[] = [];

  for (const l of layers) {
    const id = l.id;
    const sl = (l as { 'source-layer'?: string })['source-layer'];
    const type = l.type;
    const lower = id.toLowerCase();

    if (
      id.startsWith('soften-') ||
      id.startsWith('wobble-') ||
      id.startsWith('crayon-') ||
      // TERRITORY IS NOT OURS TO HIDE.
      //
      // This loop is a whitelist: anything it does not recognise as a
      // basemap layer falls through to visibility:'none' at the bottom.
      // That is right for the tiles' own furniture and wrong for layers
      // another component owns — and map/TerritoryLayer.tsx owns every
      // id under this prefix: the marks (territory-dots) and the link
      // between two of them (territory-link) are both plain style
      // layers, and both were exposed to this.
      //
      // They survive today only on ordering: the sweep runs on a palette
      // or language change, and a mark usually lands after it. Run the
      // two the other way round — change language mid-walk — and the
      // dots go out.
      //
      // WHAT IT LOOKS LIKE WHEN IT BITES, because it is not "a layer is
      // hidden": MapLibre only tiles a source that some VISIBLE layer
      // draws. Hiding these leaves a source that is present, holds the
      // right features, sits inside the viewport, and renders none of
      // them — while an identical source under a different id renders
      // fine. Found by exactly that comparison; the id was the variable.
      id.startsWith('territory-')
    ) {
      // Layers we've injected previously — re-style updates them via
      // setPaintProperty in the appropriate branch below if needed.
      continue;
    }

    if (type === 'background') {
      clear(map, id, 'background-pattern');
      map.setPaintProperty(id, 'background-color', palette.paper);
      continue;
    }

    if (sl === 'water') {
      if (type === 'fill') {
        paintFill(id, palette.blue);
        const src = (l as { source?: string }).source;
        const filt = (l as { filter?: unknown }).filter;
        if (src)
          polygonsToSoften.push({
            baseId: id,
            source: src,
            sourceLayer: 'water',
            filter: filt,
            color: palette.blue,
          });
        continue;
      }
      map.setLayoutProperty(id, 'visibility', 'none');
      continue;
    }

    if (sl === 'building') {
      if (type === 'fill') {
        paintFill(id, palette.paper);
        // Keep the flat footprint VISIBLE on the paper map even though it
        // is the same white as the page: it is what the ink outline below
        // is drawn around, and it occludes the polygon edges of anything
        // underneath, so a block reads as solid rather than as a window
        // onto the park behind it.
        if (ink) map.setLayoutProperty(id, 'visibility', 'visible');
      } else if (type === 'fill-extrusion') {
        if (ink) {
          // No volume on a line drawing. The walls are the one thing here
          // that can only be shaded, never drawn.
          map.setLayoutProperty(id, 'visibility', 'none');
        } else {
          clear(map, id, 'fill-extrusion-pattern');
          map.setPaintProperty(id, 'fill-extrusion-color', palette.paper);
          // Fully opaque so nothing shows through to grey them; the built-in
          // vertical gradient still gives walls their depth shading.
          map.setPaintProperty(id, 'fill-extrusion-opacity', 1);
        }
      }
      continue;
    }

    const isLanduseFill =
      (sl === 'landuse' || sl === 'landcover') && type === 'fill';
    const isParkLayer = sl === 'park' && type === 'fill';
    if (isLanduseFill || isParkLayer) {
      const isGreen =
        isParkLayer ||
        /park|grass|wood|forest|cemetery|recreation|pitch|meadow|farm|garden|scrub|playground|nature/.test(
          lower,
        );
      if (isGreen) {
        paintFill(id, palette.green);
        const src = (l as { source?: string }).source;
        const filt = (l as { filter?: unknown }).filter;
        if (src && sl)
          polygonsToSoften.push({
            baseId: id,
            source: src,
            sourceLayer: sl,
            filter: filt,
            color: palette.green,
          });
      } else {
        map.setLayoutProperty(id, 'visibility', 'none');
      }
      continue;
    }

    if (sl === 'transportation' && type === 'line') {
      const isCasing =
        lower.includes('casing') ||
        lower.endsWith('-bg') ||
        lower.endsWith('_bg') ||
        lower.includes('outline');
      if (isCasing) {
        map.setLayoutProperty(id, 'visibility', 'none');
        continue;
      }
      // Non-road transportation classes — rail, aerialway, ferry,
      // transit, tram, etc. — also live under the `transportation`
      // source-layer. If we apply the road pattern to them they read
      // as wide ghostly diagonals crossing the city. Hide them.
      const isNonRoad =
        /(^|[_-])(rail|railway|aerialway|cable|gondola|chair|funicular|ferry|transit|tram|monorail|subway|pier)([_-]|$)/.test(
          lower,
        );
      if (isNonRoad) {
        map.setLayoutProperty(id, 'visibility', 'none');
        continue;
      }
      // Service / construction / track / raceway — driveways, alleys,
      // dead-end utility roads. Pure noise at any zoom; hide.
      const isAlwaysHidden =
        /(^|[_-])(service|track|construction|raceway)([_-]|$)/.test(lower);
      if (isAlwaysHidden) {
        map.setLayoutProperty(id, 'visibility', 'none');
        continue;
      }
      // Path / footway / pedestrian / cycleway / steps / bridleway —
      // sidewalk doubles along streets + footpaths through parks. They
      // clutter the map (a mess of thin doubled lines) at every zoom, so
      // hide them outright rather than zoom-gating them in close.
      const isPathish =
        /(^|[_-])(path|footway|pedestrian|cycleway|steps|bridleway)([_-]|$)/.test(
          lower,
        );
      if (isPathish) {
        map.setLayoutProperty(id, 'visibility', 'none');
        continue;
      }
      clear(map, id, 'line-dasharray');
      if (ink) {
        // A drawn street has no fill and no texture — it is the stroke.
        clear(map, id, 'line-pattern');
        map.setPaintProperty(id, 'line-color', palette.greyRoad);
      } else {
        clear(map, id, 'line-color');
        map.setPaintProperty(id, 'line-pattern', 'crayon-road');
      }
      map.setPaintProperty(id, 'line-opacity', 1);
      const curW = map.getPaintProperty(id, 'line-width');
      try {
        (
          map.setPaintProperty as (l: string, p: string, v: unknown) => void
        )(id, 'line-width', scaleWidth(curW, palette.roadScale));
      } catch {
        if (typeof curW === 'number') {
          map.setPaintProperty(id, 'line-width', curW * palette.roadScale);
        }
      }
      try {
        map.setLayoutProperty(id, 'line-cap', 'round');
        map.setLayoutProperty(id, 'line-join', 'round');
      } catch {
        /* not all line layers accept these layout props */
      }
      continue;
    }

    // LABEL TIERS. text-field is locked to a single language at a
    // time (vs the bilingual "Kyiv / Київ" the OSM tile ships) — the
    // dog talks in one language, the map should match. UK is the
    // Kyiv-pilot default; flip via the in-profile language toggle.
    // Coalesce chain falls through to whatever variant the tile has
    // so unlabelled features (or missing :uk on minor streets) still
    // render with the bare name field.
    const localisedLabel =
      lang === 'uk'
        ? ['coalesce', ['get', 'name:uk'], ['get', 'name'], ['get', 'name:en']]
        : ['coalesce', ['get', 'name:en'], ['get', 'name']];
    if (sl === 'place' && type === 'symbol') {
      try {
        map.setLayoutProperty(id, 'text-field', localisedLabel);
        map.setLayoutProperty(id, 'text-font', [MAP_FONT]);
        map.setPaintProperty(id, 'text-color', palette.labelText);
        map.setPaintProperty(id, 'text-halo-color', palette.labelHalo);
        map.setPaintProperty(id, 'text-halo-width', 2);
        map.setPaintProperty(id, 'text-halo-blur', 0.5);
        map.setLayoutProperty(id, 'text-letter-spacing', 0.08);
      } catch {
        /* skip */
      }
      continue;
    }
    if (sl === 'water_name' && type === 'symbol') {
      try {
        map.setLayoutProperty(id, 'text-field', localisedLabel);
        map.setLayoutProperty(id, 'text-font', [MAP_FONT]);
        map.setPaintProperty(id, 'text-color', palette.labelWater);
        map.setPaintProperty(id, 'text-halo-color', palette.labelHalo);
        map.setPaintProperty(id, 'text-halo-width', 2);
        map.setLayoutProperty(id, 'text-letter-spacing', 0.08);
      } catch {
        /* skip */
      }
      continue;
    }
    if (sl === 'transportation_name' && type === 'symbol') {
      try {
        map.setLayoutProperty(id, 'visibility', 'visible');
        (
          map as unknown as {
            setLayerZoomRange: (id: string, min: number, max: number) => void;
          }
        ).setLayerZoomRange(id, 15, 24);
        map.setLayoutProperty(id, 'text-field', localisedLabel);
        map.setLayoutProperty(id, 'text-font', [MAP_FONT]);
        map.setPaintProperty(id, 'text-color', palette.labelStreet);
        map.setPaintProperty(id, 'text-halo-color', palette.labelHalo);
        map.setPaintProperty(id, 'text-halo-width', 1.8);
        map.setLayoutProperty(id, 'text-letter-spacing', 0.05);
      } catch {
        /* skip */
      }
      continue;
    }

    map.setLayoutProperty(id, 'visibility', 'none');
  }

  // Polygon edges — a soft same-colour halo, or a pen line on the paper
  // map. The layer is the same one either way, so a palette flip restyles
  // it in place rather than leaving the previous treatment behind.
  const edgePaint = {
    'line-width': ink ? INK_WIDTH : HALO_WIDTH,
    'line-blur': ink ? INK_BLUR : HALO_BLUR,
    'line-opacity': ink ? palette.outlineOpacity : 0.9,
  };
  const setEdge = (layerId: string, prop: string, value: unknown) => {
    (map.setPaintProperty as (l: string, p: string, v: unknown) => void)(
      layerId, prop, value,
    );
  };
  for (const p of polygonsToSoften) {
    const softId = `soften-${p.baseId}`;
    if (map.getLayer(softId)) {
      setEdge(softId, 'line-color', ink ?? p.color);
      setEdge(softId, 'line-width', edgePaint['line-width']);
      setEdge(softId, 'line-blur', edgePaint['line-blur']);
      setEdge(softId, 'line-opacity', edgePaint['line-opacity']);
      continue;
    }
    try {
      map.addLayer({
        id: softId,
        type: 'line',
        source: p.source,
        'source-layer': p.sourceLayer,
        ...(p.filter !== undefined ? { filter: p.filter } : {}),
        paint: {
          ...edgePaint,
          'line-color': ink ?? p.color,
        },
        layout: {
          'line-cap': 'round',
          'line-join': 'round',
        },
      } as LayerSpecification);
    } catch {
      /* skip silently */
    }
  }

  // Road wobble clones — light + dark grey offset shadows of each
  // transportation line. Skip layers we just hid (rail, paths, etc.)
  // so we don't draw wobble shadows under invisible features.
  const roadIds: string[] = [];
  for (const l of map.getStyle().layers ?? []) {
    const sl = (l as { 'source-layer'?: string })['source-layer'];
    if (
      l.type === 'line' &&
      sl === 'transportation' &&
      !l.id.startsWith('wobble-') &&
      (l.layout?.visibility ?? 'visible') !== 'none'
    ) {
      roadIds.push(l.id);
    }
  }
  for (const baseId of roadIds) {
    const base = map.getLayer(baseId) as
      | (LayerSpecification & {
          source?: string;
          'source-layer'?: string;
          filter?: unknown;
          minzoom?: number;
          maxzoom?: number;
        })
      | undefined;
    if (!base || !base.source || !base['source-layer']) continue;
    const lineWidth = map.getPaintProperty(baseId, 'line-width');
    // Single subtle wobble companion at +1.5 px — just enough to
    // hint at a doubled crayon stroke, not enough to read as a
    // separate cable. Two clones at ±5 with blur 2 stacked into the
    // "wires across the city" effect.
    //
    // NOT DRAWN, and that is deliberate rather than broken. These clones
    // copy the base layer's line-width, which was an expression MapLibre
    // rejected, so addLayer threw into the catch below and no wobble has
    // rendered since the road width scaling was introduced — the coloured map
    // was tuned, at length, on a street network that never had them.
    // scaleWidth() above makes the copied width valid again, so leaving
    // this on would put a doubled ghost under every road in play mode as
    // a SIDE EFFECT of a width fix, which is not a change anybody asked
    // for or looked at. Turning it back on is its own decision, with its
    // own before/after. The paper map wants no part of it either way: a
    // doubled stroke is texture, and there is no texture here.
    const WOBBLE_CLONES = false;
    const variants: Array<{ suffix: string; offset: number; color: string }> =
      WOBBLE_CLONES && !ink
        ? [{ suffix: 'lo', offset: 1.5, color: palette.roadWobbleLight }]
        : [];
    for (const v of variants) {
      const id = `wobble-${baseId}-${v.suffix}`;
      if (map.getLayer(id)) {
        map.setPaintProperty(id, 'line-color', v.color);
        continue;
      }
      try {
        map.addLayer(
          {
            id,
            type: 'line',
            source: base.source,
            'source-layer': base['source-layer'],
            ...(base.filter !== undefined ? { filter: base.filter } : {}),
            ...(base.minzoom !== undefined ? { minzoom: base.minzoom } : {}),
            ...(base.maxzoom !== undefined ? { maxzoom: base.maxzoom } : {}),
            paint: {
              'line-color': v.color,
              'line-width': lineWidth,
              'line-offset': v.offset,
              'line-opacity': 0.7,
              'line-blur': 0.8,
            },
            layout: {
              'line-cap': 'round',
              'line-join': 'round',
            },
          } as LayerSpecification,
          baseId,
        );
      } catch {
        /* skip */
      }
    }
  }

  // Building outline. Off on the coloured maps, where buildings are
  // volumes and a dark trace over the extrusion reads as grime; it is the
  // paper map's only way to draw a block at all, so the palette carries
  // the opacity rather than a constant here.
  //
  // The FINEST weight on the page, by design. Footprints outnumber every
  // other shape on a city map by an order of magnitude — at the polygon
  // edges' weight they stop being buildings and become hatching.
  const outlineOpacity = palette.buildingOutline;
  const outlineColor = palette.outline ?? palette.crayon;
  if (
    outlineOpacity > 0 &&
    buildingSource &&
    !map.getLayer('crayon-building-outline')
  ) {
    const outlineLayer: LayerSpecification = {
      id: 'crayon-building-outline',
      type: 'line',
      source: buildingSource,
      'source-layer': 'building',
      minzoom: 13,
      paint: {
        'line-color': outlineColor,
        'line-opacity': outlineOpacity,
        'line-width': [
          'interpolate', ['linear'], ['zoom'],
          13, 0.4,
          16, 0.9,
          19, 1.4,
        ],
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    } as LayerSpecification;
    map.addLayer(outlineLayer);
  } else if (buildingSource && map.getLayer('crayon-building-outline')) {
    // Layer exists from a prior render — drop it if we've disabled
    // outlines, otherwise re-sync its colour.
    if (outlineOpacity <= 0) {
      map.removeLayer('crayon-building-outline');
    } else {
      map.setPaintProperty('crayon-building-outline', 'line-color', outlineColor);
      map.setPaintProperty('crayon-building-outline', 'line-opacity', outlineOpacity);
    }
  }
}

// Show / hide the street-name labels (the `transportation_name` symbol
// layers). At the steep game pitch, road names tilt into the perspective
// and clutter the distance, so MapView hides them past the cull pitch and
// brings them back when the camera flattens out. Kept here (not in
// MapView) so the source-layer matching lives next to the rest of the
// label styling.
export function setStreetLabelsVisible(
  map: maplibregl.Map,
  visible: boolean,
): void {
  for (const l of map.getStyle().layers ?? []) {
    const sl = (l as { 'source-layer'?: string })['source-layer'];
    if (sl === 'transportation_name' && l.type === 'symbol') {
      try {
        map.setLayoutProperty(l.id, 'visibility', visible ? 'visible' : 'none');
      } catch {
        /* layer not ready / removed — skip */
      }
    }
  }
}

// ---------------------------------------------------------------------
// Style fetcher — fetch liberty's style.json, swap its glyphs URL to
// our locally-hosted Caveat PBFs, hand the mutated style to MapLibre.
// Returns the style ready to pass to `new maplibregl.Map({ style })`.
// ---------------------------------------------------------------------

//
// THE ONE FETCH THE MAP CANNOT LIVE WITHOUT, so it retries. A bare fetch
// here meant one dropped packet on a metro platform — or one slow reply
// that the browser eventually gave up on — left the app on "locating…"
// for good, with the map never constructed and no way back but a reload.
// Three attempts, each bounded (a stalled connection otherwise holds
// the map hostage for the browser's own two-minute default), with a
// short back-off between them. Total worst case is about half a minute,
// after which MapView shows a retry rather than a spinner.
const STYLE_URL = 'https://tiles.openfreemap.org/styles/liberty';
const STYLE_ATTEMPTS = 3;
const STYLE_TIMEOUT_MS = 8_000;

async function fetchStyleOnce(): Promise<Record<string, unknown>> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), STYLE_TIMEOUT_MS);
  try {
    const resp = await fetch(STYLE_URL, { signal: controller.signal });
    if (!resp.ok) throw new Error(`style ${resp.status}`);
    return (await resp.json()) as Record<string, unknown>;
  } finally {
    clearTimeout(timer);
  }
}

export async function fetchCrayonStyleSpec(): Promise<unknown> {
  let lastErr: unknown = null;
  for (let attempt = 0; attempt < STYLE_ATTEMPTS; attempt++) {
    if (attempt > 0) {
      await new Promise((r) => setTimeout(r, 1000 * attempt));
    }
    try {
      const style = await fetchStyleOnce();
      style.glyphs = `${window.location.origin}/fonts/{fontstack}/{range}.pbf`;
      return style;
    } catch (err) {
      lastErr = err;
    }
  }
  throw lastErr instanceof Error ? lastErr : new Error('style fetch failed');
}

// ---------------------------------------------------------------------
// Paper-tooth overlay sync — anchors a CSS overlay's background-position
// to a fixed lat/lng so the texture travels with the geography on pan
// (not "dirty glass" effect).
// ---------------------------------------------------------------------

export interface OverlayRef {
  current: HTMLDivElement | null;
}

export function installPaperOverlaySync(
  map: maplibregl.Map,
  overlayRef: OverlayRef,
  anchorLng: number,
  anchorLat: number,
): () => void {
  const anchor = { lng: anchorLng, lat: anchorLat };
  const initialPx = map.project(anchor);
  const sync = () => {
    const el = overlayRef.current;
    if (!el) return;
    const px = map.project(anchor);
    el.style.backgroundPosition = `${px.x - initialPx.x}px ${px.y - initialPx.y}px`;
  };
  map.on('move', sync);
  sync();
  return () => {
    map.off('move', sync);
  };
}
